import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'
import { useEffect } from 'react'

const Nav = dynamic(() => import('../components/Nav'), {
  ssr: false,
});
const Body = dynamic(() => import('../components/Body'), {
  ssr: false,
});
const Footer = dynamic(() => import('../components/Footer'), {
  ssr: false,
});
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  function reveal() {
    const reveals = document.querySelectorAll(".reveal");

    for (let i = 0; i < reveals.length; i++) {
      const windowHeight = window.innerHeight;
      const elementTop = reveals[i].getBoundingClientRect().top;
      const elementVisible = 200;
      if ((elementTop < windowHeight - elementVisible)) {
        reveals[i].classList.add("active");
      } else {
        reveals[i].classList.remove("active");
      }
    }
  }
  useEffect(()=> {
    window.addEventListener("scroll", reveal);
  },[])
  return (
    <>
      <Head>
        <title>NTF Cats</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div className="loader">
              <Image
                src="/cat-loader.svg"
                alt="Vercel Logo"
                className="logo-cat-loader"
                width={100}
                height={100}
                priority
              />
          </div>
          <Nav/>
          <div className="main">
            <Body/>
          </div>
          <Footer/>
      </main>
    </>
  )
}
